[workspace]
authors = ["Jan Ivar Korsbakken <janko@cicero.oslo.no>"]
channels = ["conda-forge"]
name = "ctsm_pylib"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
xarray = ">=2025.9.0"
tqdm = ">=4.67.1"
scipy = ">=1.16.2"
netcdf4 = ">=1.7.2"
requests = ">=2.32.5"
xesmf = ">=0.8.10"
numba = ">=0.62.1"
pylint = ">=3.3.8"
black = ">=25.1.0"
cartopy = ">=0.25.0"
matplotlib = ">=3.10.6"
pip = ">=25.2"
pytest = ">=8.4.2"
coverage = ">=7.10.7"
git = ">=2.51.0"
git-lfs = ">=3.7.0"
ncl = ">=6.6.2"
dask = ">=2025.11.0"
flox = ">=0.10.7"
cfgrib = ">=0.9.15.1"
hvplot = ">=0.12.2,<0.13"

[pypi-dependencies]
ctsm = { path = "./python", editable = true }

[feature.dev.dependencies]
ipython = "*"
ipykernel = ">=7.1.0"

[environments]
dev = ["dev"]

[activation.env]
PATH = "$PWD/cime/scripts:$PATH"
