"""Code and script to generate a mesh file land mask from the land fraction
variables in a surface data file, and add it to an existing mesh file.

The module also contains functionality to calculate the area of each element in
a mesh file. This can be helpful, since mesh files generated by
`/tools/mkmapgrids/mkscripgrid.ncl` combined with `ESMF_Scrip2Unstruct` may miss
element areas as well as the land mask. Note that this functionality currently
is restricted to regular rectangular latitude-longitude grids only.

Enums
-----
CoordDim : enum.StrEnum
    An enumeration for the coordinate dimension in a mesh file

Attributes
----------
COORD_DIM_NAMES : Mapping[CoordDim, str]
    A mapping from `CoordDim` enumeration members to their string names (i.e.,
    the `CoordDim` enum class in dictionary form).
MESH_MASK_VAR_NAME : str
    The name of the land mask variable in the output mesh file. By default
    `elementMask`.
SURFDATA_LANDFRAC_VAR_NAMES : tuple[str, ...]
    The names of the land fraction variables in the input surface data file.
    The mesh land mask will be normally be derived from points where an of the
    land fraction variables have non-zero values.
SURFDATA_COORDS_DIMS : Mapping[CoordDim, str]
    A mapping from `CoordDim` enumeration members to the names of the dimensions
    in the input surface data files.
SURFDATA_COORDS_VAR_NAMES : Mapping[CoordDim, str]
    A mapping from `CoordDim` enumeration members to the names of the names of
    the corresponding coordinate variables in surface data files. Note that the
    variables are usually two-dimensional, and therefore may not exactly
    vary along the dimension given by the respecitive key and be constant in the
    other dimension.
MESH_ELEMENT_AREA_VAR_NAME : str
    The name of the element area variable in the output mesh file. `elementArea`
    by default.
MESH_ELEMENT_AREA_ATTRS : dict[str, str]
    The attributes to add to the element area variable in the output mesh file.
    By default, this includes `long_name` (`"area weights"`) and `units`
    (`"radians^2"`).
MESH_ELEMENT_DIM_NAME : str
    The name of the element count dimension in the mesh file. By default
    `elementCount`.
MESH_CENTER_COORDS_VAR_NAME : str
    The mame of the variable that gives the center coordinates of each element
    in the mesh file. By default `centerCoords`.
MESH_COORD_DIM_NAME : str
    The name of the dimension that separates longitude and latitude coordinates
    in the mesh file. By default `coordDim`.
MESH_COORD_DIMS_INDICES : Mapping[CoordDim, int]
    A mapping that gives the index of each coordinate dimension in the mesh
    file.
MESH_LAND_MASK_ATTRS : dict[str, Any]
    The attributes to add to or set for the land mask variable in the output
    mesh file.
SURFDATA_COORD_VARS_NAMES : Mapping[CoordDim, str]
    A mapping that gives the names of the longitude and latitude coordinate
    variables in the surface data files.

Functions
---------
make_latlon_1d_indexed(
    ds: xarray.Dataset,
    *,
    input_index_var_names: Mapping[CoordDim, str] | None = None,
    input_index_dim: str,
    output_index_dim: str,
    input_multidim_index_var_name: str | None = None,
    input_multidim_index_coord_dim_name: str | None = None,
    input_multidim_index_coord_indices: Mapping[CoordDim, int] | None = None,
    output_index_level_names: Mapping[CoordDim, str],
) -> xarray.Dataset
    Add a coordinate index with longitude and latitude coordinates as levels to
    a Dataset that has a 1D element-based dimension and longitudes/latitudes
    either as two separate variables or as components along a coordinate
    coordinate dimension in a single variable (e.g., like `centerCoords` in ESMF
    mesh files).
create_land_mask_from_landfrac(
    source_ds: xarray.Dataset,
    *,
    landfrac_var_names: Sequence[str] = SURFDAT_LANDFRAC_VAR_NAMES,
    landmask_var_name: str = MESH_MASK_VAR_NAME,
    landfrac_threshold: float = 0.0,
    land_mask_attrs: dict[str, tp.Any] | None = None,
) -> xarray.DataArray
    Create a land mask DataArray from land fraction variables in a surface data
    Dataset. By default, points with land fraction values greater than 0.0 for
    any listed land fraction variable are considered land. The threshold can be
    customized.
compute_mesh_element_areas(
    mesh_ds: xarray.Dataset | Path | str,
) -> esmpy.Field
    Compute the area of each element in a mesh Dataset. Returns the areas as an
    esmpy.Field object, in the units used by `esmpy.Field.get_area()` (usually
    radians^2, i.e., normalized to 4*pi).
write_output_mesh_file(
    mesh_ds: xarray.Dataset,
    output_path: Path,
    *,
    format: nc4.Dataset.Format|None = None,
    clobber: bool = False,
) -> None
    Write the modified mesh Dataset to a new netCDF file.
lonlat2d_to_mesh_coords(
    lonlat_ds: xr.Dataset,
    mesh_ds: xr.Dataset,
    *,
    lon_var_name: str = 'LONGXY',
    lat_var_name: str = 'LATIXY',
    lon_dim_name: str = 'lsmlon',
    lat_dim_name: str = 'lsmlat',
    mesh_center_coords_var_name: str = 'centerCoords',
    mesh_element_dim_name: str = 'elementCount',
    mesh_coord_dim_name: str = 'coordDim',
) -> xr.Dataset
    Convert an xarray Dataset with 2D longitude and latitude dimensions to the
    1D element-based coordinate system used in a mesh Dataset. NB! Not correctly
    implemented yet.
"""
import argparse
from collections.abc import (
    Mapping,
    Sequence,
)
import enum
import itertools
import logging
from pathlib import Path
import sys
import tempfile
import typing as tp

import netCDF4 as nc4
import xarray as xr



logger: tp.Final[logging.Logger] = logging.getLogger(__name__)

class CoordDim(enum.StrEnum):
    """An enumeration for the coordinate dimension in a mesh file.

    Members
    -------
    LON : str
        Represents the longitude coordinate dimension.
    LAT : str
        Represents the latitude coordinate dimension.
    """

    LON = 'lon'
    LAT = 'lat'
###END class CoordDim

COORD_DIM_NAMES: tp.Final[Mapping[CoordDim, str]] = {
    _member: _member.value for _member in CoordDim
}


MESH_MASK_VAR_NAME: tp.Final[str] = 'elementMask'

MESH_LAND_MASK_ATTRS: tp.Final[dict[str, tp.Any]] = {}

SURFDATA_LANDFRAC_VAR_NAMES: tp.Final[tuple[str, ...]] = (
    'LANDFRAC_PFT',
    'LANDFRAC_MKSURFDATA',
)

SURFDATA_COORD_DIMS: tp.Final[Mapping[CoordDim, str]] = {
    CoordDim.LON: 'lsmlon',
    CoordDim.LAT: 'lsmlat',
}

SURFDATA_COORDS_VAR_NAMES: tp.Final[Mapping[CoordDim, str]] = {
    CoordDim.LON: 'LONGXY',
    CoordDim.LAT: 'LATIXY',
}

MESH_ELEMENT_AREA_VAR_NAME: tp.Final[str] = 'elementArea'

MESH_ELEMENT_AREA_ATTRS: tp.Final[dict[str, str]] = {
    'long_name': 'area weights',
    'units': 'radians^2',
}

MESH_ELEMENT_DIM_NAME: tp.Final[str] = 'elementCount'

MESH_CENTER_COORDS_VAR_NAME: tp.Final[str] = 'centerCoords'

MESH_COORD_DIM_NAME: tp.Final[str] = 'coordDim'

MESH_COORD_DIMS_INDICES: tp.Final[Mapping[CoordDim, int]] = {
    CoordDim.LON: 0,
    CoordDim.LAT: 1,
}


_UNITS_ATTR_NAME: tp.Final[str] = 'units'


def make_latlon_1d_indexed(
    ds: xr.Dataset,
    *,
    input_index_dim: str,
    output_index_dim: str | None = None,
    output_index_level_names: Mapping[CoordDim, str],
    input_index_var_names: Mapping[CoordDim, str] | None = None,
    input_multidim_index_var_name: str | None = None,
    input_multidim_index_coord_dim_name: str | None = None,
    input_multidim_index_coord_indices: Mapping[CoordDim, int] | None = None,
) -> xr.Dataset:
    """Add a coordinate index with longitude and latitude coordinates as levels
    to a Dataset that has a 1D element-based dimension and longitudes/latitudes
    either as two separate variables or as components along a coordinate
    coordinate dimension in a single variable (e.g., like `centerCoords` in ESMF
    mesh files).

    If the input Dataset has separate longitude and latitude variables, specify
    those variables in `input_index_var_names`. If the input Dataset has a
    single multidimensional variable with a coordinate dimension (e.g., like
    `centerCoords` in ESMF mesh files), specify the variable name in
    `input_multidim_index_var_name`, the name of the coordinate dimension in
    `input_multidim_index_coord_dim_name`, and which indices along that
    dimension correspond to longitude and latitude in
    `input_multidim_index_coord_indices`.

    Either `input_index_var_names` or `input_multidim_index_var_name`,
    `input_multidim_index_coord_dim_name`, and
    `input_multidim_index_coord_indices` must be specified, but only one of
    those sets.

    Parameters
    ----------
    ds : xarray.Dataset
        The input Dataset with a 1D element-based dimension.
    input_index_dim : str
        The name of the 1D element-based dimension in `ds`.
    output_index_dim : str | None, optional
        The name of the output coordinate index dimension to add to `ds`.
        Optional, defaults to `input_index_dim`.
    output_index_level_names : Mapping[CoordDim, str]
        A mapping from `CoordDim` enumeration members to the names of the levels
        in the output coordinate index that will represent longitude and
        latitude (which will then also act as coordinate variables for the
        same).
    input_index_var_names : Mapping[CoordDim, str] | None, optional
        Specify this if `ds` has a separate variable for each longitude/latitude
        coordinate. Must be a mapping from `CoordDim` enumeration members to the names of the
        longitude and latitude variables in `ds`.  Mutually exclusive with
        `input_multidim_index_var_name`. By default `None`.
    input_multidim_index_var_name : str | None, optional
        Specify this if `ds` has a single multidimensional variable with a
        coordinate dimension (e.g., like `centerCoords` in ESMF mesh files).
        The name of the variable in `ds` that contains both longitude and
        latitude coordinates along a coordinate dimension. Mutually exclusive
        with `input_index_var_names`. By default `None`.
    input_multidim_index_coord_dim_name : str | None, optional
        The name of the coordinate dimension in the variable given by
        `input_multidim_index_var_name` that separates longitude and latitude
        coordinates. Required if `input_multidim_index_var_name` is specified.
        By default `None`. Mutually exclusive with `input_index_var_names`.
    input_multidim_index_coord_indices : Mapping[CoordDim, int] | None, optional
        A mapping from `CoordDim` enumeration members to the indices along the
        coordinate dimension in the variable given by
        `input_multidim_index_var_name` that correspond to longitude and
        latitude coordinates. Required if `input_multidim_index_var_name` is
        specified. By default `None`. Mutually exclusive with
        `input_index_var_names`.

    Returns
    -------
    xarray.Dataset
        The modified Dataset with the added coordinate index.
    """
    if (
            (input_index_var_names is None)
            == (input_multidim_index_var_name is None)
    ):
        raise ValueError(
            'Either input_index_var_names or input_multidim_index_var_name '
            'must be specified, but not both.'
        )
    if output_index_dim is None:
        output_index_dim = input_index_dim

    coord_vars: dict[CoordDim, xr.DataArray]
    if input_index_var_names is not None:
        if set(input_index_var_names.keys()) != set(CoordDim):
            raise ValueError(
                'input_index_var_names must have exactly the following keys: '
                f'{set(CoordDim)}'
            )
        index_level_coords: dict[CoordDim, xr.DataArray] = {
            _coord_dim: ds[input_index_var_names[_coord_dim]]
            for _coord_dim in CoordDim
        }
    else:
        if (
                input_multidim_index_coord_dim_name is None
                or input_multidim_index_coord_indices is None
        ):
            raise ValueError(
                'If input_multidim_index_var_name is specified, both '
                'input_multidim_index_coord_dim_name and '
                'input_multidim_index_coord_indices must also be specified.'
            )
        if set(input_multidim_index_coord_indices.keys()) != set(CoordDim):
            raise ValueError(
                'input_multidim_index_coord_indices must have exactly the '
                f'following keys: {set(CoordDim)}'
            )
        index_var: xr.DataArray = ds[input_multidim_index_var_name]
        index_level_coords: dict[CoordDim, xr.DataArray] = {
            _coord_dim: index_var.isel(
                {
                    input_multidim_index_coord_dim_name:
                        input_multidim_index_coord_indices[_coord_dim]
                }
            )
            for _coord_dim in CoordDim
        }
        del index_var

    ds = ds.assign_coords(
        {
            output_index_level_names[_coord_dim]: index_level_coords[_coord_dim]
            for _coord_dim in CoordDim
        }
    )
    del index_level_coords
    ds = ds.set_index(
        {
            output_index_dim: list(output_index_level_names.values())
        }
    )
    return ds
###END def make_latlon_1d_indexed




def create_land_mask_from_landfrac(
    source_ds: xr.Dataset,
    *,
    landfrac_var_names: tp.Sequence[str] = SURFDATA_LANDFRAC_VAR_NAMES,
    landmask_var_name: str = MESH_MASK_VAR_NAME,
    landfrac_threshold: float = 0.0,
    land_mask_attrs: dict[str, tp.Any] | None = None,
) -> xr.DataArray:
    """Create a land mask DataArray from land fraction variables in a surface
    data Dataset. By default, points with land fraction values greater than 0.0
    for any listed land fraction variable are considered land. The threshold
    can be customized.

    Parameters
    ----------
    source_ds : xarray.Dataset
        The input surface data Dataset containing land fraction variables.
    landfrac_var_names : Sequence[str], optional
        The names of the land fraction variables to consider, by default
        `SURFDAT_LANDFRAC_VAR_NAMES`.
    landmask_var_name : str, optional
        The name of the output land mask variable, by default
        `MESH_MASK_VAR_NAME`.
    landfrac_threshold : float, optional
        The threshold above which a land fraction value is considered land,
        by default 0.0.
    land_mask_attrs : dict[str, Any] | None, optional
        Attributes to assign to the land mask DataArray. Optional. If
        unspecified or None, the module attribute `MESH_LAND_MASK_ATTRS` is
        used.

    Returns
    -------
    xarray.DataArray
        A DataArray representing the land mask, with 1 for points containing
        land, and 0 for ocean points.
    """
    if not isinstance(landfrac_var_names, tp.Sequence):
        raise TypeError(
            'landfrac_var_names must be a sequence of strings, '
            f'got {type(landfrac_var_names)}'
        )
    if isinstance(landfrac_var_names, str):
        landfrac_var_names = [landfrac_var_names]
    if not all(isinstance(name, str) for name in landfrac_var_names):
        raise TypeError(
            'all elements of landfrac_var_names must be strings'
        )
    mask_array: xr.DataArray = (
        source_ds[landfrac_var_names[0]] > landfrac_threshold
    )
    for var_name in landfrac_var_names[1:]:
        mask_array |= (source_ds[var_name] > landfrac_threshold)
    mask_array = mask_array.astype('int32')
    mask_array.name = landmask_var_name
    mask_array.attrs = (
        land_mask_attrs if land_mask_attrs is not None
        else MESH_LAND_MASK_ATTRS
    )
    return mask_array
###END def create_land_mask_from_landfrac


def compute_mesh_element_areas(
    mesh: xr.Dataset | Path | str,
    *,
    mesh_element_dim_name: str = MESH_ELEMENT_DIM_NAME,
    mesh_area_var_name: str = MESH_ELEMENT_AREA_VAR_NAME,
    mesh_area_attrs: dict[str, str] = MESH_ELEMENT_AREA_ATTRS,
) -> xr.DataArray:
    """Compute the area of each element in a mesh Dataset.

    Note that the function relies on creating an `esmpy.Mesh` object from file
    in order to avoid manually having to create nodes and stagger locations. As
    a result, if an `xarray.Dataset` is provided as input, it will first be
    written to a temporary netCDF file before being read by `esmpy`. The
    temporary file will be removed before returning.

    In order to avoid unnecessary imports, the `esmpy` module is only imported
    when this function is first called.

    Parameters
    ----------
    mesh_ds : xarray.Dataset
        The input mesh Dataset. Must be an ESMF mesh file.

    Returns
    -------
    xarray.DataArray
        A DataArray containing the area of each element in the mesh Dataset. The
        areas are in the units used by `esmpy.Field.get_area()` (usually
        radians^2, i.e., normalized to 4*pi). The returned data array is 1d with
        dimension given by `mesh_element_dim_name`. If `mesh` is an
        `xarray.Dataset`, the ordering of elements will match it so that the
        DataArray can be directly added to the Dataset, but note that the
        DataArray will not have any coordinates or an index. These must be added
        from the original mesh Dataset if needed.
    """
    import esmpy
    if isinstance(mesh, (str, Path)):
        mesh_obj: esmpy.Mesh = esmpy.Mesh(
            filename=str(mesh),
            filetype=esmpy.FileFormat.ESMFMESH,
        )
    else:
        with tempfile.NamedTemporaryFile(
            suffix='.nc',
            prefix='temp_mesh_',
            delete=True,
        ) as temp_mesh_file:
            mesh_path = Path(temp_mesh_file.name)
            mesh.to_netcdf(mesh_path)
            mesh_obj: esmpy.Mesh = esmpy.Mesh(
                filename=str(mesh_path),
                filetype=esmpy.FileFormat.ESMFMESH,
            )
    area_field: esmpy.Field = esmpy.Field(
        grid=mesh_obj,
        name='elementArea',
        meshloc=esmpy.MeshLoc.ELEMENT,
    )
    area_field.get_area()
    area_arr: xr.DataArray = xr.DataArray(
        data=area_field.data,
        dims=(mesh_element_dim_name,),
        attrs=mesh_area_attrs,
    )
    area_field.destroy()
    mesh_obj.destroy()
    del area_field, mesh_obj
    return area_arr
###END def compute_mesh_element_areas


def write_output_mesh_file(
    mesh_ds: xr.Dataset,
    output_path: Path|str,
    *,
    format: str | None = None,
    clobber: bool = False,
) -> None:
    """Write a modified mesh Dataset to a new netCDF file.

    Parameters
    ----------
    mesh_ds : xarray.Dataset
        The modified mesh Dataset.
    output_path : Path | str
        The path to the output netCDF file.
    format : Literal['NETCDF4', 'NETCDF4_CLASSIC', 'NETCDF3_64BIT',
            'NETCDF3_CLASSIC'] | None, optional
        The netCDF format to use for the output file. If `None`, the function
        will attempt to infer and use the format of the original mesh file if
        `mesh_ds.encoding['source']` exists. Otherwise, `NETCDF4` will be used
        by default.
    """
    if format is None:
        source_path: str | None = mesh_ds.encoding.get('source', None)
        if source_path is not None:
            try:
                with nc4.Dataset(source_path, mode='r') as src_nc4:
                    format = src_nc4.file_format
                    logger.debug(
                        f'Inferred NetCDF format "{format}" from source mesh '
                        f'file "{source_path}".'
                    )
                    if format.startswith('NETCDF3_64BIT'):
                        format = 'NETCDF3_64BIT'
            except Exception as exc:
                logger.warning(
                    f'Error when trying to open source mesh file '
                    f'"{source_path}" to infer NetCDF format. Please specify '
                    f'the format explicitly through the `format` parameter to '
                    'avoid this error, or ensure that the source file exists, '
                    'is readable, and can be read by `netCDF4.Dataset`.'
                )
        else:
            logger.warning(
                'The mesh Dataset does not specify a source file in '
                '`mesh_ds.encoding["source"]`. Using NETCDF4 by default. '
                'Specify the `format` parameter explicitly to avoid this '
                'warning.'
            )
            format = 'NETCDF4'
    if Path(output_path).exists() and not clobber:
        raise FileExistsError(
            f'Output file "{output_path}" already exists. To overwrite, set '
            'the `clobber` parameter to True.'
        )
    if format not in (
            'NETCDF4',
            'NETCDF4_CLASSIC',
            'NETCDF3_64BIT',
            'NETCDF3_CLASSIC',
    ):
        raise ValueError(
            f'Invalid NetCDF format "{format}". Must be one of '
            '"NETCDF4", "NETCDF4_CLASSIC", "NETCDF3_64BIT", or '
            '"NETCDF3_CLASSIC"'
        )
    mesh_ds.to_netcdf(
        path=output_path,
        format=format,
    )
    logger.info(f'Wrote output mesh file to "{output_path}".')
###END def write_output_mesh_file


def _get_different_name(
    name: str,
    existing_names: tp.Iterable[str],
    *,
    add_char: str = '_',
) -> str:
    """Helper function to get a name that is not in a collection of existing
    names.

    The function appends `add_char` to `name` until a name is found that is not
    in `existing_names`.

    Parameters
    ----------
    name : str
        The base name to modify if it already exists in `existing_names`.
    existing_names : Iterable[str]
        An iterable of existing names to avoid.
    add_char : str, optional
        The character to append to `name` if it already exists in
        `existing_names`, by default '_'

    Returns
    -------
    str
        A name that is not in `existing_names`, and equal to `name` if that name
        was not in `existing_names`.
    """
    new_name: str = name
    while new_name in existing_names:
        new_name += add_char
    return new_name
###END def _get_different_name


class MeshCenterCoordsVarExistsError(ValueError):
    """Error raised when the center coordinates variable already exists in a
    Dataset where it is to be added.
    """

    def __init__(
            self,
            *args,
            var_name: str,
    ) -> None:
        """Initialize the error.

        Parameters
        ----------
        var_name : str
            The name of the center coordinates variable that already exists.
        """
        self.var_name: str = var_name
        super().__init__(
            *args if args else (
                f'Trying to add mesh center coordinates variable "{var_name}", '
                'but it already exists in the Dataset.'
            )
        )
    ###END def MeshCenterCoordsVarExistsError.__init__

###END class MeshCenterCoordsVarExistsError


def lonlat2d_to_mesh_coords(
    lonlat_ds: xr.Dataset,
    mesh_ds: xr.Dataset | None = None,
    *,
    lon_var_name: str = 'LONGXY',
    lat_var_name: str = 'LATIXY',
    lon_dim_name: str = 'lsmlon',
    lat_dim_name: str = 'lsmlat',
    mesh_center_coords_var_name: str = MESH_CENTER_COORDS_VAR_NAME,
    mesh_element_dim_name: str = MESH_ELEMENT_DIM_NAME,
    mesh_coord_dim_name: str = MESH_COORD_DIM_NAME,
    keep_lon_lat_vars: bool = True,
) -> xr.Dataset:
    """Convert an xarray Dataset with 2D longitude and latitude dimensions to
    the 1D element-based coordinate system used in a mesh Dataset.

    Parameters
    ----------
    lonlat_ds : xarray.Dataset
        The input Dataset containing variables that depend on the 2D longitude
        dimensions, and variables with the longitude and latitude coordinates.
        The longitude and latitude variabbles are not required to be registered
        as coordinate variables, since that is not necessarily the case in
        surface data files.
    mesh_ds : xarray.Dataset, optional
        A Dataset from a mesh file, which contains the dimensions and coordinate
        variables that `lonlat_ds` should be mapped to. If not provided,
        `lonlat_ds` will be stacked to an element-based coordinate system as
        used in mesh files, but without aligning it to a specific mesh file.
        In order to add data from the returned Dataset to a specific mesh file,
        it must first be aligned, since the ordering of elements may differ.
    lon_var_name : str, optional
        The name of the longitude variable in `lonlat_ds`, by default
        `'LONGXY'`. In general, the variable is assumed to be 2D, with
        dimensions equal to those given by both `lon_dim_name` and
        `lat_dim_name`. **NB!** The variable must contain the exact same values
        as are found in the longitude values in the mesh file variable given by
        `mesh_center_coords_var_name`.
    lat_var_name : str, optional
        The name of the latitude variable in `lonlat_ds`, by default `'LATIXY'`.
        In general, the variable is assumed to be 2D, with dimensions equal to
        those given by both `lon_dim_name` and `lat_dim_name`. **NB!** The
        variable must contain the exact same values as are found in the latitude
        values in the mesh file variable given by `mesh_center_coords_var_name`.
    lon_dim_name : str, optional
        The name of the longitude dimension in `lonlat_ds`, by default
        `'lsmlon'`.
    lat_dim_name : str, optional
        The name of the latitude dimension in `lonlat_ds`, by default
        `'lsmlat'`.
    mesh_center_coords_var_name : str, optional
        The name of the center coordinates variable in `mesh_ds`, by default
        given by the module attribute `MESH_CENTER_COORDS_VAR_NAME`.
    mesh_element_dim_name : str, optional
        The name of the element dimension in `mesh_ds`, by default given by the
        module attribute `MESH_ELEMENT_DIM_NAME`.
    mesh_coord_dim_name : str, optional
        The name of the coordinate dimension in `mesh_ds`, by default given by
        the module attribute `MESH_COORD_DIM_NAME`. This dimension is assumed to
        have size 2, with the first index representing longitude and the second
        index representing latitude.
    keep_lon_lat_vars : bool, optional
        Whether to keep the longitude and latitude variables given by
        `lon_var_name` and `lat_var_name` in the returned Dataset. By default
        `True`. If `False`, the variables will be removed from the returned
        Dataset (but the values are retained in the variable given by
        `mesh_center_coords_var_name`).

    Returns
    -------
    xarray.Dataset
        A new dataset with the same variables as `lonlat_ds`, but mapped to the
        a 1D coordinate system as used in mesh files, and with the coordinate
        variable given by `mesh_center_coords_var_name` added. If `mesh_ds` is
        provided, the mapping will be aligned to the element ordering in
        `mesh_ds`.
    """
    if (
            mesh_center_coords_var_name in lonlat_ds.variables
            or mesh_center_coords_var_name in lonlat_ds.dims
    ):
        raise MeshCenterCoordsVarExistsError(
            var_name=mesh_center_coords_var_name
        )
    lonlat_ds_stacked: xr.Dataset = lonlat_ds.stack(
        dim={mesh_element_dim_name: (lon_dim_name, lat_dim_name)},
        create_index=False,
    )
    def _combine_attrs(
            attrs: Sequence[dict[str, str]],
            context: tp.Any,
    ) -> dict[str, str]:
        if len(attrs) != 2:
            return dict()
        if all(
            _attrs.get(_UNITS_ATTR_NAME, '').lower().startswith('degrees')
            for _attrs in attrs
        ):
            return {_UNITS_ATTR_NAME: 'degrees'}
        return dict()
    ###END def _combine_attrs
    lonlat_ds_stacked[mesh_center_coords_var_name] = xr.concat(
        [
            lonlat_ds_stacked[lon_var_name],
            lonlat_ds_stacked[lat_var_name],
        ],
        dim=mesh_coord_dim_name,
        combine_attrs=_combine_attrs,
    )
    if mesh_ds is not None:
        # Align to the mesh Dataset by reindexing according to the center
        # coordinates variable in the mesh Dataset.
        lonlat_ds_stacked = align_mesh_center_coords(
            lonlat_ds_stacked,
            align_to=mesh_ds,
            center_coords_var_name=mesh_center_coords_var_name,
        )
    if not keep_lon_lat_vars:
        lonlat_ds_stacked = lonlat_ds_stacked.drop_vars(
            (lon_var_name, lat_var_name)
        )
    return lonlat_ds_stacked
###END def lonlat2d_to_mesh_coords


def main() -> None:
    """Main function for the script to generate a mesh land mask from surface
    data.
    """
    parser = argparse.ArgumentParser(
        description=(
            'Generate a mesh land mask from land fraction variables in a '
            'surface data file, and add it t an existing mesh file.'
            '\n\nBy default also adds element areas to the mesh file (can be '
            'disabled.'
        )
    )
    parser.add_argument(
        '--mesh-file',
        type=Path,
        help='Path to the input mesh netCDF file.',
        required=True,
    )
    parser.add_argument(
        '--surfdata-file',
        type=Path,
        help='Path to the input surface data netCDF file.',
        required=True,
    )
    parser.add_argument(
        '--output-mesh-file',
        type=Path,
        help='Path to the output mesh netCDF file.',
        required=True,
    )
    parser.add_argument(
        '--surfdata-landfrac-vars',
        type=str,
        nargs='+',
        default=list(SURFDATA_LANDFRAC_VAR_NAMES),
        help='List of land fraction variable names in the surface data file '
        'to use for generating the land mask, by default '
        f'{SURFDATA_LANDFRAC_VAR_NAMES}.',
    )
    parser.add_argument(
        '--add-element-areas',
        type=bool,
        default=True,
        help='Whether to compute and add element areas to the output mesh '
        'file, by default True.',
    )
    parser.add_argument(
        '--log-level',
        type=str,
        default='INFO',
        help='Logging level, by default "INFO".',
    )

    args: argparse.Namespace = parser.parse_args()
    logging.basicConfig(level=args.log_level)
    mesh_file: Path = args.mesh_file
    output_mesh_file: Path = args.output_mesh_file
    surfdata_file: Path = args.surfdata_file
    surfdata_landfrac_vars: list[str] = args.surfdata_landfrac_vars
    mesh_mask_var_name: str = MESH_MASK_VAR_NAME
    mesh_element_area_var_name: str = MESH_ELEMENT_AREA_VAR_NAME

    logger.info(f'Opening mesh file: {mesh_file}...')
    mesh_ds: xr.Dataset = xr.open_dataset(
        mesh_file,
        cache=True,
    )

    logger.info(f'Opening and 1d-stacking surface data file: {surfdata_file}...')
    surfdata_ds: xr.Dataset = xr.open_dataset(
        surfdata_file,
        cache=True,
    )
    surfdata_ds = make_latlon_1d_indexed(
        surfdata_ds.drop_vars(
            _var for _var in surfdata_ds.data_vars.keys()
            if _var not in tuple(
                itertools.chain(
                    SURFDATA_LANDFRAC_VAR_NAMES,
                    SURFDATA_COORDS_VAR_NAMES.values()
                )
            )
        ).stack(
            dim={MESH_ELEMENT_DIM_NAME: tuple(SURFDATA_COORD_DIMS.values())},
            create_index=False,
        ),
        input_index_var_names=SURFDATA_COORDS_VAR_NAMES,
        input_index_dim=MESH_ELEMENT_DIM_NAME,
        output_index_dim=MESH_ELEMENT_DIM_NAME,
        output_index_level_names=COORD_DIM_NAMES,
    )

    logger.info(
        'Creating land mask from surface data land fraction variables...'
    )
    mesh_mask_arr: xr.DataArray = create_land_mask_from_landfrac(
        surfdata_ds,
        landfrac_var_names=surfdata_landfrac_vars,
    )

    logger.info('Indexing the mesh file dataset...')
    mesh_ds = make_latlon_1d_indexed(
        mesh_ds,
        input_index_dim=MESH_ELEMENT_DIM_NAME,
        output_index_dim=MESH_ELEMENT_DIM_NAME,
        input_multidim_index_var_name=MESH_CENTER_COORDS_VAR_NAME,
        input_multidim_index_coord_dim_name=MESH_COORD_DIM_NAME,
        input_multidim_index_coord_indices=MESH_COORD_DIMS_INDICES,
        output_index_level_names=COORD_DIM_NAMES,
    )

    logger.info(
        f'Adding land mask to mesh dataset as variable {mesh_mask_var_name}...'
    )
    if mesh_mask_var_name in mesh_ds.variables:
        logger.warning(
            f'Variable {mesh_mask_var_name} already exists in the mesh '
            'dataset and will be overwritten.'
        )
    mesh_ds[mesh_mask_var_name] = mesh_mask_arr.reindex_like(mesh_ds)
    logger.debug(
        'Adding attributes to the mesh land mask variable...',
        extra={
            'original_attrs': mesh_ds[mesh_mask_var_name].attrs,
            'new_attrs': MESH_LAND_MASK_ATTRS,
        },
    )
    mesh_ds[mesh_mask_var_name].attrs.update(MESH_LAND_MASK_ATTRS)
    del mesh_mask_arr
    surfdata_ds.close()

    if args.add_element_areas:
        logger.info(
            'Computing and adding element areas to the mesh dataset as '
            f'variable {mesh_element_area_var_name}...'
        )
        mesh_area_arr: xr.DataArray = compute_mesh_element_areas(mesh_ds)
        if mesh_element_area_var_name in mesh_ds.variables:
            logger.warning(
                f'Variable {mesh_element_area_var_name} already exists in '
                'the mesh dataset and will be overwritten.'
            )
        mesh_ds[mesh_element_area_var_name] = mesh_area_arr
        logger.debug(
            'Adding attributes to the mesh element area variable...',
            extra={
                'original_attrs': mesh_ds[mesh_element_area_var_name].attrs,
                'new_attrs': MESH_ELEMENT_AREA_ATTRS,
            },
        )
        mesh_ds[mesh_element_area_var_name].attrs.update(
            MESH_ELEMENT_AREA_ATTRS
        )
        del mesh_area_arr

    logger.info(f'Writing output mesh file: {output_mesh_file}...')
    write_output_mesh_file(
        mesh_ds,
        output_mesh_file,
    )
    mesh_ds.close()

###END def main


if __name__ == '__main__':
    main()

    # ###
    # Code to move to new function to align mesh datasets, or to create lon/lat
    # coordinate variables in mesh datasets.
    # ###
    # avoid_var_names: tp.Final[set[str]] = {
    #     mesh_center_coords_var_name,
    #     mesh_element_dim_name,
    #     mesh_coord_dim_name,
    # }
    # new_lon_var_name: str = _get_different_name(lon_var_name, avoid_var_names)
    # new_lat_var_name: str = _get_different_name(lat_var_name, avoid_var_names)
    # # Determine whether the lon/lat variables are already coordinates and need
    # # to be reverted to regular variables at the end of the process.
    # revert_coords: set[str] = set(
    #     _new_var_name for _new_var_name, _orig_var_name in (
    #         (new_lon_var_name, lon_var_name),
    #         (new_lat_var_name, lat_var_name),
    #     ) if _orig_var_name not in lonlat_ds.coords
    # )
    # lonlat_ds_stacked = lonlat_ds_stacked.rename_vars(
    #     {
    #         _orig_var_name: _new_var_name
    #         for _new_var_name, _orig_var_name in (
    #             (new_lon_var_name, lon_var_name),
    #             (new_lat_var_name, lat_var_name),
    #         ) if _orig_var_name != _new_var_name
    #     }
    # )
    # lonlat_ds_stacked = lonlat_ds_stacked.set_coords(
    #     (new_lon_var_name, new_lat_var_name)
    # )