"""Code and script to generate a mesh file land mask from the land fraction
variables in a surface data file, and add it to an existing mesh file.

The module also contains functionality to calculate the area of each element in
a mesh file. This can be helpful, since mesh files generated by
`/tools/mkmapgrids/mkscripgrid.ncl` combined with `ESMF_Scrip2Unstruct` may miss
element areas as well as the land mask. Note that this functionality currently
is restricted to regular rectangular latitude-longitude grids only.

Attributes
----------
MESH_MASK_VAR_NAME : str
    The name of the land mask variable in the output mesh file. By default
    `elementMask`.
SURFDAT_LANDFRAC_VAR_NAMES : tuple[str, ...]
    The names of the land fraction variables in the input surface data file.
    The mesh land mask will be normally be derived from points where an of the
    land fraction variables have non-zero values.
MESH_ELEMENT_AREA_VAR_NAME : str
    The name of the element area variable in the output mesh file. `elementArea`
    by default.
MESH_ELEMENT_AREA_ATTRS : dict[str, str]
    The attributes to add to the element area variable in the output mesh file.
    By default, this includes `long_name` (`"area weights"`) and `units`
    (`"radians^2"`).

Functions
---------
create_land_mask_from_landfrac(
    source_ds: xarray.Dataset,
    *,
    landfrac_var_names: Sequence[str] = SURFDAT_LANDFRAC_VAR_NAMES,
    landmask_var_name: str = MESH_MASK_VAR_NAME,
    landfrac_threshold: float = 0.0,
    land_mask_attrs: dict[str, tp.Any] | None = None,
) -> xarray.DataArray
    Create a land mask DataArray from land fraction variables in a surface data
    Dataset. By default, points with land fraction values greater than 0.0 for
    any listed land fraction variable are considered land. The threshold can be
    customized.
compute_regular_rect_element_areas(
    mesh_ds: xarray.Dataset,
    *,
    latitudes: xarray.DataArray,
    longitudes: xarray.DataArray,
) -> xarray.DataArray
write_output_mesh_file(
    mesh_ds: xarray.Dataset,
    output_path: Path,
) -> None
    Write the modified mesh Dataset to a new netCDF file.

"""
import argparse
from collections.abc import Sequence
from pathlib import Path
import typing as tp

import xarray as xr



MESH_MASK_VAR_NAME: tp.Final[str] = 'elementMask'

MESH_LAND_MASK_ATTRS: tp.Final[dict[str, tp.Any]] = {}

SURFDAT_LANDFRAC_VAR_NAMES: tp.Final[tuple[str, ...]] = (
    'LANDFRAC_PFT',
    'LANDFRAC_MKSURFDATA',
)

MESH_ELEMENT_AREA_VAR_NAME: tp.Final[str] = 'elementArea'

MESH_ELEMENT_AREA_ATTRS: tp.Final[dict[str, str]] = {
    'long_name': 'area weights',
    'units': 'radians^2',
}


def create_land_mask_from_landfrac(
    source_ds: xr.Dataset,
    *,
    landfrac_var_names: tp.Sequence[str] = SURFDAT_LANDFRAC_VAR_NAMES,
    landmask_var_name: str = MESH_MASK_VAR_NAME,
    landfrac_threshold: float = 0.0,
    land_mask_attrs: dict[str, tp.Any] | None = None,
) -> xr.DataArray:
    """Create a land mask DataArray from land fraction variables in a surface
    data Dataset. By default, points with land fraction values greater than 0.0
    for any listed land fraction variable are considered land. The threshold
    can be customized.

    Parameters
    ----------
    source_ds : xarray.Dataset
        The input surface data Dataset containing land fraction variables.
    landfrac_var_names : Sequence[str], optional
        The names of the land fraction variables to consider, by default
        `SURFDAT_LANDFRAC_VAR_NAMES`.
    landmask_var_name : str, optional
        The name of the output land mask variable, by default
        `MESH_MASK_VAR_NAME`.
    landfrac_threshold : float, optional
        The threshold above which a land fraction value is considered land,
        by default 0.0.
    land_mask_attrs : dict[str, Any] | None, optional
        Attributes to assign to the land mask DataArray. Optional. If
        unspecified or None, the module attribute `MESH_LAND_MASK_ATTRS` is
        used.

    Returns
    -------
    xarray.DataArray
        A DataArray representing the land mask, with 1 for points containing
        land, and 0 for ocean points.
    """
    STACK_DIM: str = '__STACK_DIM__'
    if not isinstance(landfrac_var_names, tp.Sequence):
        raise TypeError(
            'landfrac_var_names must be a sequence of strings, '
            f'got {type(landfrac_var_names)}'
        )
    if isinstance(landfrac_var_names, str):
        landfrac_var_names = [landfrac_var_names]
    if not all(isinstance(name, str) for name in landfrac_var_names):
        raise TypeError(
            'all elements of landfrac_var_names must be strings'
        )
    mask_array: xr.DataArray = (
        source_ds[landfrac_var_names[0]] > landfrac_threshold
    )
    for var_name in landfrac_var_names[1:]:
        mask_array |= (source_ds[var_name] > landfrac_threshold)
    mask_array = mask_array.astype('int32')
    mask_array.name = landmask_var_name
    mask_array.attrs = (
        land_mask_attrs if land_mask_attrs is not None
        else MESH_LAND_MASK_ATTRS
    )
    return mask_array
###END def create_land_mask_from_landfrac
